Progetto_ML_LabInf: Porgetto_Matteo_Luceri.c File Reference
Porgetto_Matteo_Luceri.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "main.h"
#include "f_all_shared.h"
#include "f_disp.h"
#include "f_edit_client.h"
#include "f_new_pren.h"
#include "f_out_remove_pren.h"
Functions
int main (void)
Function Documentation
main()
int main (void)
Definition at line 20 of file Porgetto_Matteo_Luceri.c.
References leggi_conta_csv_clienti(), leggi_conta_csv_prenotazioni(), login(), modifica_dati(), modifica_prenotazione_tipo_ombrellone(), ombrelloni_disponibili_fila(), ombrelloni_disponibili_fila_cresc_decr(), prenota_ombrellone(), rimuovi_prenotazione(), salva_prenotazioni_per_data(), stampa_clienti(), and stampa_prenotazione().