Progetto_ML_LabInf: f_all_shared.h File Reference
f_all_shared.h File Reference
Functions
double login (cliente_t [], int)
int leggi_conta_csv_clienti (cliente_t [])
int leggi_conta_csv_prenotazioni (prenotazione_t [])
int verifica_email (char [], cliente_t [], int, int *)
int verifica_password (char [], cliente_t [], int)
int controllo_data (int, data_t)
void stampa_prenotazione (prenotazione_t [], int)
double calcola_totale (double, ombrellone_t, int, int, int)
void stampa_tipo (int)
int confronta_prenotazione_data_input (prenotazione_t [], int, data_t)
int controlla_tipo_giornata (int, int)
void stampa_ombrelloni_liberi (pren_ombr_disponibile_t)
void verifica_disp_tutti_ombrelloni (prenotazione_t [], data_t, int, int, int, ombrellone_t [])
void stampa_a_video_prenotazione (prenotazione_t)
Function Documentation
calcola_totale()
double calcola_totale (double sconto_u, ombrellone_t ombr_i, int tipo_i, int lettini_i, int sedie_i)
La funzione calcola il totale oggetto di una nuova prenotazione
Parameters
sconto_u,sconto da applicare alla prenotazione dell'utente
ombr_i,varibile tipo ombrellone contente fila, ombrellone della nuova prenotazione
tipo_i,il tipo di prenotazione della nuova prenotazione
lettini_i,il numero di lettini della nuova prenotazione
sedie_i,il numero di sedie della nuova prenotazione
Returns
ritorno il costo totale
La funzione calcola il totale oggetto di una nuova prenotazione
Parameters
sconto_u sconto da applicare alla prenotazione dell'utente
ombr_i varibile tipo ombrellone contente fila, ombrellone della nuova prenotazione
tipo_i,il tipo di prenotazione della nuova prenotazione
lettini_i il numero di lettini della nuova prenotazione
sedie_i il numero di sedie della nuova prenotazione
Returns
ritorno il costo totale
Definition at line 513 of file f_all_shared.c.
References ombrellone_t::fila_o.
Referenced by modifica_prenotazione_tipo_ombrellone(), and prenota_ombrellone().
confronta_prenotazione_data_input()
int confronta_prenotazione_data_input (prenotazione_t pre[], int num_p, data_t data_in)
Funzione che confronta una data in input cone le date delle prenotazioni e restituisce, all'avvenire della condizione, l'indice della prenotazione in oggetto
Parameters
pre,array di strutture prenotazione
num_p,numero di prenotazioni
data_in,data in input dall'utente
Returns
, ritorna l'indice della prenotazione oppure 0
Definition at line 312 of file f_all_shared.c.
References data_t::anno, prenotazione_t::data, data_t::giorno, and data_t::mese.
Referenced by ombrelloni_disponibili_fila(), and prenota_ombrellone().
controlla_tipo_giornata()
int controlla_tipo_giornata (int tipo_p, int doppia_p_a)
La funzione prende il tipo e il flag doppia prenotazione e calcola la disponibilità relativa ad essa
Parameters
tipo_p,il tipo di prenotazione
doppia_p_a,flag,>1 se ho già due prenotazioni in quel giorno
Returns
Definition at line 355 of file f_all_shared.c.
Referenced by modifica_tipo_prenotazione(), ombrelloni_disponibili_fila(), and verifica_disp_tutti_ombrelloni().
controllo_data()
int controllo_data (int gma, data_t data_gma)
La funzione verificherà se una data ricevuta in input dall'utente sarà ben formata
Parameters
gma,benchè il nome poco significativo, la variabile ha lo scopo di "potenziare' la funzione. Infatti grazie un ulteriore controllo potrò verificare o meno , anche date "odierne" e che quindi non saranno minori dell'anno corrente.
data_gma,la data oggetto del controllo
Returns
errore, se errore sarà > 0 allora il controllo avrà esito negativo
Definition at line 256 of file f_all_shared.c.
References data_t::anno, anno_corrente, data_t::giorno, and data_t::mese.
Referenced by modifica_dati(), ombrelloni_disponibili_fila(), ombrelloni_disponibili_fila_cresc_decr(), and prenota_ombrellone().
leggi_conta_csv_clienti()
int leggi_conta_csv_clienti (cliente_t cli[])
Funzione di lettura da file del csv clienti. Inoltre ritorno il numero di righe
Parameters
cli,l'array di strutture clienti
Returns
il numero delle righe del file
Funzione di lettura da file del csv clienti. Inoltre ritorno il numero di righe
Parameters
cli l'array di strutture clienti
Returns
tighe il numero delle righe del file
Definition at line 121 of file f_all_shared.c.
References data_t::anno, data_t::giorno, data_t::mese, cliente_t::nascita, and cliente_t::sconto.
Referenced by main().
leggi_conta_csv_prenotazioni()
int leggi_conta_csv_prenotazioni (prenotazione_t pren[])
Funzione di lettura da file del csv prenotazioni. Inoltre ritorno il numero di righe il procedimento è analogo a quello visto nella funzione precedente
Parameters
pren,l'array di strutture prenotazione
Returns
il numero delle righe del file in oggetto
Definition at line 163 of file f_all_shared.c.
References data_t::anno, prenotazione_t::cod, prenotazione_t::costo, prenotazione_t::data, ombrellone_t::fila_o, data_t::giorno, data_t::mese, prenotazione_t::num_lettini, prenotazione_t::num_ombrellone, prenotazione_t::num_sedie, ombrellone_t::ombrellone, and prenotazione_t::tipo.
Referenced by main(), and rimuovi_prenotazione().
login()
double login (cliente_t cli[], int num_cli)
La funzione permetterà mediante confronto di verificare l'accesso degli utenti registrati
Parameters
cli,l'array della struttura clienti
num_cli,il numero dei clienti
Returns
ritornerà il l'indice del cliente o , -1 indicante un valore negativo che idicherà l'errore al sistema
La funzione permetterà mediante confronto di verificare l'accesso degli utenti registrati
Parameters
cli l'array della struttura clienti
num_cli il numero dei clienti
Returns
ritornerà il l'indice del cliente o -1 indicante un valore negativo che idicherà l'errore al sistema
Definition at line 22 of file f_all_shared.c.
References verifica_email(), and verifica_password().
Referenced by main().
stampa_a_video_prenotazione()
void stampa_a_video_prenotazione (prenotazione_t pren)
La funzione stampa a video una prenotazione data per input
Parameters
pren,array di strutture prenotazione
La funzione stampa a video una prenotazione data per input
Parameters
pren array di strutture prenotazione
Definition at line 494 of file f_all_shared.c.
References data_t::anno, prenotazione_t::cod, prenotazione_t::costo, prenotazione_t::data, prenotazione_t::email, ombrellone_t::fila_o, data_t::giorno, data_t::mese, prenotazione_t::num_lettini, prenotazione_t::num_ombrellone, prenotazione_t::num_sedie, ombrellone_t::ombrellone, stampa_tipo(), and prenotazione_t::tipo.
Referenced by modifica_prenotazione_tipo_ombrellone(), and rimuovi_prenotazione().
stampa_ombrelloni_liberi()
void stampa_ombrelloni_liberi (pren_ombr_disponibile_t ombr_disp_a)
La funzione acquisita la struttura contenente le disponibilità di una determinata fila, la stamperà a video
Parameters
ombr_disp_a,struttura fila di ombrelloni
Definition at line 378 of file f_all_shared.c.
References ombrellone_t::check, max_ombrelloni, ombrellone_t::ombrellone, and pren_ombr_disponibile_t::ombrelloni.
Referenced by ombrelloni_disponibili_fila(), and verifica_disp_tutti_ombrelloni().
stampa_prenotazione()
void stampa_prenotazione (prenotazione_t pren_a[], int num_pren_a)
La funzione stamperà le prenotazioni dall'array di strutture prenotazione
Parameters
pren_a,array di strutture prenotazione
num_pren_a,numero delle prenotazioni
La funzione stamperà le prenotazioni dall'array di strutture prenotazione
Parameters
pren_a array di strutture prenotazione
num_pren_a numero delle prenotazioni
Definition at line 552 of file f_all_shared.c.
References data_t::anno, prenotazione_t::costo, prenotazione_t::data, ombrellone_t::fila_o, data_t::mese, prenotazione_t::num_lettini, prenotazione_t::num_ombrellone, prenotazione_t::num_sedie, ombrellone_t::ombrellone, and prenotazione_t::tipo.
Referenced by main(), modifica_prenotazione_tipo_ombrellone(), and rimuovi_prenotazione().
stampa_tipo()
void stampa_tipo (int tipo_i)
La funzione stamperà a video l'equivalente numerico della tipologia di prenotazione
Parameters
tipo_i,il tipo, oggetto di una prenotazione
Definition at line 336 of file f_all_shared.c.
Referenced by modifica_tipo_prenotazione(), prenota_ombrellone(), and stampa_a_video_prenotazione().
verifica_disp_tutti_ombrelloni()
void verifica_disp_tutti_ombrelloni (prenotazione_t prenotazioni_a[], data_t data_i_a, int num_p_a, int crdecr, int indice, ombrellone_t ombr_a[])
La funzione verifica la disponibilità di tutte le file e gli ombrelloni per una specifica data
Parameters
prenotazioni_a,array di strutture prenotazione
data_i_a,data inserita dall'utente
num_p_a,numero di prenotazioni
crdecr,variabile di controllo per lo switch , oltre che stabilire l'ordinamente crescente o decrescente
indice,l'indice oggetto di una determinata prenotazione
ombr_a,l'ombrellone inserito
Definition at line 411 of file f_all_shared.c.
References data_t::anno, ombrellone_t::check, controlla_tipo_giornata(), prenotazione_t::data, ombrellone_t::doppia_prenotazione, ombrellone_t::fila_o, data_t::giorno, max_file, max_ombrelloni, data_t::mese, prenotazione_t::num_ombrellone, ombrellone_t::ombrellone, pren_ombr_disponibile_t::ombrelloni, and stampa_ombrelloni_liberi().
Referenced by modifica_num_ombrellone_prenotazione(), modifica_tipo_prenotazione(), and ombrelloni_disponibili_fila_cresc_decr().
verifica_email()
int verifica_email (char strg_a[], cliente_t strg_b[], int num_clienti, int * indice)
Confronta due stringhe email, ritorno quante prenotazioni effettua un cliente
Parameters
strg_a,stringa a , corrisponderà all'e-mail da in input dal utente
strg_b,stringa b, sarà invece l'email in possesso al sistema mediante file
num_clienti,il numero dei clienti
indice,il puntatore permette di ritornare l'indice
Returns
ritorno verifica, se > 0, il confronto è avvenuto con successo
Definition at line 205 of file f_all_shared.c.
Referenced by login().
verifica_password()
int verifica_password (char strg_a[], cliente_t strg_b[], int num_clienti)
Confornta due stringhe password. Il procedimento è analogo a quello visto nella funzione precedente
Parameters
strg_a,stringa a , corrisponderà alla password data in input dal utente
strg_b,stringa b, sarà invece la password in possesso al sistema mediante file
num_clienti,il numero dei clienti
Returns
ritorno verifica, se > 0, il confronto è avvenuto con successo
Definition at line 230 of file f_all_shared.c.
Referenced by login().