Progetto_ML_LabInf: f_disp.c File Reference
f_disp.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "main.h"
#include "f_disp.h"
#include "f_all_shared.h"
Functions
void ombrelloni_disponibili_fila (prenotazione_t prenotazioni_a [], int num_p_a)
int confronta_prenotazione_fila (prenotazione_t pre[], ombrellone_t ombr, int num_p)
void ombrelloni_disponibili_fila_cresc_decr (prenotazione_t prenotazioni_a [], int num_p_a)
void modifica_prenotazione_tipo_ombrellone (prenotazione_t prenotazione[], int num_prenotazioni, int indice, int num_clienti, cliente_t client [])
void modifica_tipo_prenotazione (prenotazione_t prenotazione[], int indice, int num_pren)
void modifica_num_ombrellone_prenotazione (prenotazione_t prenotazione[], int indice, int num_pren)
Function Documentation
confronta_prenotazione_fila()
int confronta_prenotazione_fila (prenotazione_t pre[], ombrellone_t ombr, int num_p)
Confronto il numero di fila dato input dall'utente con le file oggetto di una prenotazione
Parameters
pre,array di strutture prenotazione
ombr,variabile di tipo ombrellone inserita dall'utente
num_p,numero di prenotazioni
Returns
ritorno il valore di verifica, > 0 sse il confronto è positivo
Definition at line 124 of file f_disp.c.
References ombrellone_t::fila_o, and max_file.
Referenced by ombrelloni_disponibili_fila().
modifica_num_ombrellone_prenotazione()
void modifica_num_ombrellone_prenotazione (prenotazione_t prenotazione[], int indice, int num_pren)
La funzione modifica il numero di ombrellone qualora possibile
Parameters
prenotazione,array di strutture prenotazione
indice,indice del cliente che ha fatto l'accesso
num_pren,numero di prenotazioni
Definition at line 428 of file f_disp.c.
References prenotazione_t::data, max_ombrelloni, prenotazione_t::num_ombrellone, ombrellone_t::ombrellone, and verifica_disp_tutti_ombrelloni().
Referenced by modifica_prenotazione_tipo_ombrellone().
modifica_prenotazione_tipo_ombrellone()
void modifica_prenotazione_tipo_ombrellone (prenotazione_t prenotazione[], int num_prenotazioni, int indice, int num_clienti, cliente_t client[])
La funzione permette di modificare il tipo di prenotazione e/o l'ombrellone, a scelta dell'utente
Parameters
prenotazione,array di strutture prenotazione
num_prenotazioni,numero di prenotazioni
indice,indice del cliente che ha fatto l'accesso
num_clienti,il numero di clienti
client,array di strutture cliente
Definition at line 204 of file f_disp.c.
References calcola_totale(), modifica_num_ombrellone_prenotazione(), modifica_tipo_prenotazione(), stampa_a_video_prenotazione(), and stampa_prenotazione().
Referenced by main().
modifica_tipo_prenotazione()
void modifica_tipo_prenotazione (prenotazione_t prenotazione[], int indice, int num_pren)
La funzione modifica il tipo di una prenotazione quando possibile
Parameters
prenotazione,array di strutture prenotazione
indice,indice del cliente che ha fatto l'accesso
num_pren,numero di prenotazioni
Definition at line 324 of file f_disp.c.
References data_t::anno, controlla_tipo_giornata(), prenotazione_t::data, max_ombrelloni, data_t::mese, stampa_tipo(), prenotazione_t::tipo, and verifica_disp_tutti_ombrelloni().
Referenced by modifica_prenotazione_tipo_ombrellone().
ombrelloni_disponibili_fila()
void ombrelloni_disponibili_fila (prenotazione_t prenotazioni_a[], int num_p_a)
La funzione verificherà la disponibilità di quali ombrelloni sono liberi della fila specificata dal cliente in una certa data
Parameters
prenotazioni_a,array di strutture prenotazione
num_p_a,numero di prenotazioni
Definition at line 21 of file f_disp.c.
References data_t::anno, ombrellone_t::check, confronta_prenotazione_data_input(), confronta_prenotazione_fila(), controlla_tipo_giornata(), controllo_data(), prenotazione_t::data, ombrellone_t::doppia_prenotazione, ombrellone_t::fila_o, data_t::giorno, max_file, max_ombrelloni, data_t::mese, ombrellone_t::ombrellone, pren_ombr_disponibile_t::ombrelloni, and stampa_ombrelloni_liberi().
Referenced by main().
ombrelloni_disponibili_fila_cresc_decr()
void ombrelloni_disponibili_fila_cresc_decr (prenotazione_t prenotazioni_a[], int num_p_a)
La funzione acquisita una data dall'utente restituisce la disponibilità ti tutti gli ombrelloni, ordinando le file in ordine a scelta crescente o decrescente
Parameters
prenotazioni_a,array di strutture prenotazione
num_p_a,numero di prenotazioni
Definition at line 152 of file f_disp.c.
References data_t::anno, controllo_data(), data_t::giorno, max_ombrelloni, data_t::mese, and verifica_disp_tutti_ombrelloni().
Referenced by main().