Progetto_ML_LabInf: f_edit_client.h File Reference
f_edit_client.h File Reference
Functions
void modifica_dati (cliente_t [], int, int)
void stampa_clienti (cliente_t [], int)
Function Documentation
modifica_dati()
void modifica_dati (cliente_t cli[], int indice, int num_cli)
La funzione permette la modifica dei campi clienti , eccenzion fatta per email
Parameters
cli,l'array di strutture clienti
indice,l'indice del cliente che vuole effettuare le modifiche
num_cli,il numero dei clienti
Definition at line 23 of file f_edit_client.c.
References controllo_data(), and stampa_clienti().
Referenced by main().
stampa_clienti()
void stampa_clienti (cliente_t cli_a[], int num_cli_a)
Stampo l'array di strutture cliente nel file clienti.csv
Parameters
cli_a,l'array di strutture cliente
num_cli_a,il numero dei clienti
Definition at line 135 of file f_edit_client.c.
References data_t::anno, data_t::mese, cliente_t::nascita, and cliente_t::sconto.
Referenced by main(), and modifica_dati().