Progetto_ML_LabInf: f_new_pren.c File Reference
f_new_pren.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "main.h"
#include "f_new_pren.h"
#include "f_all_shared.h"
Functions
void prenota_ombrellone (prenotazione_t pren[], int num_pren, cliente_t cli[], int index)
int confronta_prenotazione_num_ombrellone_fila (prenotazione_t pre[], ombrellone_t ombr)
void stampa_nuova_prenotazione (cliente_t cli_a[], int index_a, data_t data_a, ombrellone_t ombr_a, prenotazione_t pren_a[], int num_pren_a, int tipo_a, int lettini_a, int sedie_a, double totale)
int tipo_mpg ()
int lettini ()
int sedie ()
Function Documentation
confronta_prenotazione_num_ombrellone_fila()
int confronta_prenotazione_num_ombrellone_fila (prenotazione_t pre[], ombrellone_t ombr)
La funzione prima verifica che il numero di ombrellone e fila siano validi. Dopo di che verifica che non esistano prenotazioni già effettuate con la stessa fila ed ombrellone. Inoltre verifico il tipo di prenotazione. Infatti se tipo = 3 (giornata intera) la prenotazione non potrà effettuarsi
Parameters
pre,array di strutture prenotazione
ombr,struttura ombrellone ,data in input dall'utente
Returns
ritorno l'indice della prenotazione trovata, altrimenti 0. Inoltre verifico il tipo, ritornando i valori mediante la struttura ombrellone
Definition at line 163 of file f_new_pren.c.
References ombrellone_t::check, ombrellone_t::fila_o, max_file, max_ombrelloni, prenotazione_t::num_ombrellone, ombrellone_t::ombrellone, and prenotazione_t::tipo.
Referenced by prenota_ombrellone().
lettini()
int lettini ()
La funzione acquisisce e restituisce il numero di lettini oggetto di una nuova prenotazione mediante l'input dell'utente
Returns
, ritorno il numero di lettini
Definition at line 257 of file f_new_pren.c.
Referenced by prenota_ombrellone().
prenota_ombrellone()
void prenota_ombrellone (prenotazione_t pren[], int num_pren, cliente_t cli[], int index)
La procedura permetterà la prenotazione di un ombrellone in una determinata data
Parameters
pren,array di strutture prenotazione
num_pren,numero di prenotazioni
cli,array di strutture cliente
index,l'indice relativo al cliente che ha eseguito l'accesso
Definition at line 23 of file f_new_pren.c.
References data_t::anno, calcola_totale(), ombrellone_t::check, confronta_prenotazione_data_input(), confronta_prenotazione_num_ombrellone_fila(), controllo_data(), ombrellone_t::fila_o, data_t::giorno, lettini(), data_t::mese, ombrellone_t::ombrellone, cliente_t::sconto, sedie(), stampa_nuova_prenotazione(), stampa_tipo(), and tipo_mpg().
Referenced by main().
sedie()
int sedie ()
La funzione acquisisce e restituisce il numero di sedie oggetto di una nuova prenotazione mediante l'input dell'utente
Returns
, ritorno il numero di sedie
Definition at line 293 of file f_new_pren.c.
Referenced by prenota_ombrellone().
stampa_nuova_prenotazione()
void stampa_nuova_prenotazione (cliente_t cli_a[], int index_a, data_t data_a, ombrellone_t ombr_a, prenotazione_t pren_a[], int num_pren_a, int tipo_a, int lettini_a, int sedie_a, double totale)
La funzione stamperà insieme alle vecchie prenotazioni anche una nuova prenotazione
Parameters
cli_a,array di strurre cliente
index_a,indice del cliente che ha eseguito l'acesso
data_a,data della nuova prenotazione
ombr_a,ombrellone della nuova prenotazione
pren_a,array di strutture prenotazione (acquisito da file)
num_pren_a,numero deelle prenotazioni
tipo_a,tipo di prenotazione della nuova prenotazione
lettini_a,lettini della nuova prenotazione
sedie_a,sedie della nuova prenotazione
totale,costo totale della nuova prenotazione
Definition at line 208 of file f_new_pren.c.
References data_t::anno, ombrellone_t::fila_o, data_t::giorno, data_t::mese, and ombrellone_t::ombrellone.
Referenced by prenota_ombrellone().
tipo_mpg()
int tipo_mpg ()
La funzione acquisisce e restituisce il tipo di prenotazione mediante l'input dell'utente
Returns
, ritorno il tipo di prenotazione
Definition at line 230 of file f_new_pren.c.
Referenced by prenota_ombrellone().