Progetto_ML_LabInf: f_out_remove_pren.c File Reference
f_out_remove_pren.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "main.h"
#include "f_out_remove_pren.h"
#include "f_all_shared.h"
Functions
void rimuovi_prenotazione (prenotazione_t pren [], int num_p, cliente_t client)
void stampa_rimuovi_prenotazione (prenotazione_t pren_a [], int num_p, int num_sel)
void salva_prenotazioni_per_data (prenotazione_t pren[], int num_p)
void ordinamento_prenotazioni_data (prenotazione_t pren [], int num_p)
int data_estesa (int giorno, int mese, int anno)
Function Documentation
data_estesa()
int data_estesa (int giorno, int mese, int anno)
La funzione transformera la struttura data in un unico campo intero
Parameters
giorno,campi della struttura data
mese,"
anno,"
Returns
ritorno la data per esteso (formato aaaammgg)
Definition at line 267 of file f_out_remove_pren.c.
Referenced by ordinamento_prenotazioni_data(), and salva_prenotazioni_per_data().
ordinamento_prenotazioni_data()
void ordinamento_prenotazioni_data (prenotazione_t pren[], int num_p)
La funzione ordina le prenotazioni per data
Parameters
pren,array di strutture prenotazione
num_p,numero di prenotazioni
Definition at line 229 of file f_out_remove_pren.c.
References data_t::anno, prenotazione_t::data, data_estesa(), and data_t::mese.
Referenced by salva_prenotazioni_per_data().
rimuovi_prenotazione()
void rimuovi_prenotazione (prenotazione_t pren[], int num_p, cliente_t client)
La funzione rimuoverà una prenotazione a scelta fra quelle dell'utente
Parameters
pren,array di strutture prenotazione
num_p,numero di prenotazioni
client,array di strutture cliente
Definition at line 22 of file f_out_remove_pren.c.
References prenotazione_t::cod, cliente_t::cognome, cliente_t::email, leggi_conta_csv_prenotazioni(), cliente_t::nome, stampa_a_video_prenotazione(), stampa_prenotazione(), and stampa_rimuovi_prenotazione().
Referenced by main().
salva_prenotazioni_per_data()
void salva_prenotazioni_per_data (prenotazione_t pren[], int num_p)
La funzione permette il salvataggio fisico, previo ordinamento, di tutte le prenotazioni divise per data
Parameters
pren,array di strutture prenotazione
num_p,numero delle prenotazioni
Definition at line 147 of file f_out_remove_pren.c.
References data_t::anno, prenotazione_t::costo, prenotazione_t::data, data_estesa(), ombrellone_t::fila_o, data_t::mese, prenotazione_t::num_lettini, prenotazione_t::num_ombrellone, prenotazione_t::num_sedie, ombrellone_t::ombrellone, ordinamento_prenotazioni_data(), and prenotazione_t::tipo.
Referenced by main().
stampa_rimuovi_prenotazione()
void stampa_rimuovi_prenotazione (prenotazione_t pren_a[], int num_p, int num_sel)
La funzione rimuove una prenotazione non stampadola ed aggiorna il csv delle prenotazioni
Parameters
pren_a,array di strutture prenotazione
num_p,numero delle prenotazioni
num_sel,il codice della prenotazione da eliminare (proveniente dall'array di indici
Definition at line 117 of file f_out_remove_pren.c.
References data_t::anno, prenotazione_t::costo, prenotazione_t::data, ombrellone_t::fila_o, data_t::mese, prenotazione_t::num_lettini, prenotazione_t::num_ombrellone, prenotazione_t::num_sedie, ombrellone_t::ombrellone, and prenotazione_t::tipo.
Referenced by rimuovi_prenotazione().